In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import numpy as np
import scipy as sc
from numpy.random import rand
from time import time
import swarming

In [73]:
ini = swarming.InitialCondition(n_particles=1000)
swarm = swarming.Model(*ini.square, rhs=swarming.rep_attr_rhs)

In [74]:
from bokeh.plotting import figure, ColumnDataSource
from bokeh.io import show, output_notebook, push_notebook
output_notebook()

Loading BokehJS ...

In [75]:
cds = ColumnDataSource(data=swarm.cds_dict())

In [76]:
f = figure(title="quiver", plot_width=400, plot_height=400, match_aspect=True)
f.circle(x="x1", y="x2", source=cds)
f.multi_line(xs="x1s", ys="x2s", source=cds)

handle = show(f, notebook_handle=True)

In [77]:
cds.data = swarm.evolve(.5).cds_dict()
push_notebook(handle=handle)

In [42]:
ini = swarming.InitialCondition(n_particles=4)
X, V = ini.circular

In [30]:
V

array([[ 0.20653326,  0.97843958],
       [-0.78084395,  0.62472612],
       [ 0.96682844, -0.25542663],
       [-0.95593541,  0.29357705]])

In [31]:
np.flip(V, axis=1)

array([[ 0.97843958,  0.20653326],
       [ 0.62472612, -0.78084395],
       [-0.25542663,  0.96682844],
       [ 0.29357705, -0.95593541]])

In [27]:
from swarming import rep_attr_potential

force = rep_attr_potential()
x1, x2 = np.meshgrid(X[:, 0], X[:, 0])
distx1 = x1 - x2
x1, x2 = np.meshgrid(X[:, 1], X[:, 1])
distx2 = x1 - x2
normdi = np.sqrt(distx1**2 + distx2**2)
np.stack((
    np.sum(force(normdi)/((np.abs(normdi-0)<1e-14).astype(int) +normdi)*distx1, axis=0),
    np.sum(force(normdi)/((np.abs(normdi-0)<1e-14).astype(int) +normdi)*distx2, axis=0)
)).T

array([[-3.37194436e+00,  2.19157558e+00],
       [ 3.09079384e+00, -1.93341392e+00],
       [ 3.88149448e-01, -2.61371968e-01],
       [-1.06998926e-01,  3.21031237e-03]])

In [9]:
f = figure()
x=np.linspace(0, 50, 100)
f.line(x=x, y=force(x))
show(f)